In [1]:
import pandas as pd

In [2]:
df_his_index=pd.read_csv("../../processed/his_index_tech_500_stable_14_24.csv")

In [4]:
df_his_index["Date"]=pd.to_datetime(df_his_index["Date"])

In [5]:
df_his_index

,Date,tech_weight,Open,High,Low,Close,Open_wi,High_wi,Low_wi,Close_wi,Timedelta_days,pro_change_close_wi
0,2014-01-02,18.666742,1845.86,1845.86,1827.74,1831.98,344.561924,344.561924,341.179510,341.970980,0,-0.751953
1,2014-01-03,18.575319,1833.21,1838.24,1829.13,1831.37,340.524605,341.458944,339.766732,340.182820,1,-0.522898
2,2014-01-06,18.617887,1832.31,1837.16,1823.73,1826.77,341.137405,342.040373,339.539991,340.105974,3,-0.022589
3,2014-01-07,18.672965,1828.71,1840.10,1828.71,1837.88,341.474378,343.601229,341.474378,343.186689,1,0.905810
4,2014-01-08,18.639790,1837.90,1840.02,1831.40,1837.49,342.580700,342.975864,341.369114,342.504277,1,-0.198846
...,...,...,...,...,...,...,...,...,...,...,...,...
2563,2024-10-24,37.089590,5817.80,5817.80,5784.92,5809.86,2157.798167,2157.798167,2145.603110,2154.853254,1,0.014143
2564,2024-10-25,37.319370,5826.75,5862.82,5799.98,5808.12,2174.506391,2187.967488,2164.515996,2167.553793,1,0.589392
2565,2024-10-28,37.250240,5833.93,5842.92,5823.08,5823.52,2173.152926,2176.501723,2169.111275,2169.275176,3,0.079416
2566,2024-10-29,37.562030,5819.68,5847.19,5802.17,5832.92,2185.989948,2196.323262,2179.412836,2190.963160,1,0.999780
2567,2024-10-30,37.506520,5832.65,5850.94,5811.28,5813.67,2187.624039,2194.483981,2179.608895,2180.505301,1,-0.477318

In [6]:
lst_dates_care=df_his_index["Date"].to_list()

As a reminder, there is missing values starting 2016-12-31 and ending 2017-07-05.

Create new dataframe for all values.

In [8]:
df_collection=pd.DataFrame({"Date":lst_dates_care})

Including the pro change of closing index of weighted index of tech industry stable companies in s and p 500.

In [10]:
df_collection["tech_index_pro_change"]=df_his_index["pro_change_close_wi"]

Including the prochange of copper daily price.

In [12]:
df_cop=pd.read_csv("../../processed/cop_daily_we_care.csv")

In [14]:
df_collection["cop_daily_pro_change"]=df_cop["pro_change"]

Include the pro change of gold daily price.

In [16]:
df_gold=pd.read_csv("../../processed/gold_daily_we_care.csv")

In [18]:
df_collection["gold_daily_pro_change"]=df_gold["pro_change"]

Include pro change of silver daily price.

In [21]:
df_silv=pd.read_csv("../../processed/silv_daily_we_care.csv")

In [23]:
df_collection["silv_daily_pro_change"]=df_silv["pro_change"]

Include pro change of palladium daily price.

In [26]:
df_pal=pd.read_csv("../../processed/pal_daily_we_care.csv")

In [28]:
df_collection["pal_daily_pro_change"]=df_pal["pro_change"]

Include pro change of platinum daily price.

In [30]:
df_plat=pd.read_csv("../../processed/plat_daily_we_care.csv")

In [32]:
df_collection["plat_daily_pro_change"]=df_plat["pro_change"]

Include pro change of crude oil daily price.

In [34]:
df_crude_oil=pd.read_csv("../../processed/crude_oil_we_care.csv")

In [36]:
df_collection["crude_oil_daily_pro_change"]=df_crude_oil["pro_change"]

Include fed rate.

In [38]:
df_fed=pd.read_csv("../../processed/fed_rate_we_care.csv")

In [40]:
df_collection["fed_dff"]=df_fed["DFF"]

Following is the data frame with all daily values.

In [41]:
df_collection

,Date,tech_index_pro_change,cop_daily_pro_change,gold_daily_pro_change,silv_daily_pro_change,pal_daily_pro_change,plat_daily_pro_change,crude_oil_daily_pro_change,fed_dff
0,2014-01-02,-0.751953,-0.352994,-0.105993,3.539095,0.828394,1.134643,-3.106599,0.08
1,2014-01-03,-0.522898,-0.783676,0.000000,0.000000,0.130092,0.683469,-1.550712,0.08
2,2014-01-06,-0.022589,0.134128,1.044727,-0.124205,0.998359,0.155565,-0.564070,0.08
3,2014-01-07,0.905810,0.000000,-0.678514,-1.571905,0.433311,-0.070602,0.256877,0.07
4,2014-01-08,-0.198846,-0.506028,-0.333442,-1.253348,-0.458406,-0.084782,-1.430554,0.07
...,...,...,...,...,...,...,...,...,...
2563,2024-10-24,0.014143,0.886590,0.713997,-0.130653,7.209738,0.382858,-0.753162,4.83
2564,2024-10-25,0.589392,-0.073233,0.208295,-0.038653,2.969432,-0.168621,2.162085,4.83
2565,2024-10-28,0.079416,0.000000,0.051054,0.666270,-98.982188,0.847772,-6.124737,4.83
2566,2024-10-29,0.999780,-0.073287,0.918501,1.273490,9891.666667,1.759734,-0.253807,4.83
2567,2024-10-30,-0.477318,-0.110011,1.155735,-0.583516,-5.921601,-4.042113,2.050591,4.83

Change a name for tech_index_pro_change. And fed_dff.

In [45]:
df_collection=df_collection.rename(columns={"tech_index_pro_change":"tech_index_daily_pro_change", "fed_dff":"fed_dff_daily"})

In [46]:
df_collection

,Date,tech_index_daily_pro_change,cop_daily_pro_change,gold_daily_pro_change,silv_daily_pro_change,pal_daily_pro_change,plat_daily_pro_change,crude_oil_daily_pro_change,fed_dff_daily
0,2014-01-02,-0.751953,-0.352994,-0.105993,3.539095,0.828394,1.134643,-3.106599,0.08
1,2014-01-03,-0.522898,-0.783676,0.000000,0.000000,0.130092,0.683469,-1.550712,0.08
2,2014-01-06,-0.022589,0.134128,1.044727,-0.124205,0.998359,0.155565,-0.564070,0.08
3,2014-01-07,0.905810,0.000000,-0.678514,-1.571905,0.433311,-0.070602,0.256877,0.07
4,2014-01-08,-0.198846,-0.506028,-0.333442,-1.253348,-0.458406,-0.084782,-1.430554,0.07
...,...,...,...,...,...,...,...,...,...
2563,2024-10-24,0.014143,0.886590,0.713997,-0.130653,7.209738,0.382858,-0.753162,4.83
2564,2024-10-25,0.589392,-0.073233,0.208295,-0.038653,2.969432,-0.168621,2.162085,4.83
2565,2024-10-28,0.079416,0.000000,0.051054,0.666270,-98.982188,0.847772,-6.124737,4.83
2566,2024-10-29,0.999780,-0.073287,0.918501,1.273490,9891.666667,1.759734,-0.253807,4.83
2567,2024-10-30,-0.477318,-0.110011,1.155735,-0.583516,-5.921601,-4.042113,2.050591,4.83

In [47]:
df_collection.to_csv("../../processed/all_data_collection.csv", index=False)