In [1]:
import pandas as pd

In [2]:
df_tech_500=pd.read_csv("../processed/tech_sp500_stable_extended_tickers.csv")

Here, we are using stable companies between 2014 to 2024.

In [4]:
df_tech_500[df_tech_500["stable 14 to 24"]==True]

,Unnamed: 0,cik,name,entityType,sic,sicDescription,ownerOrg,insiderTransactionForOwnerExists,insiderTransactionForIssuerExists,tickers,...,business_street1,business_street2,business_city,business_stateOrCountry,business_zipCode,business_stateOrCountryDescription,naics,stable 12 to 24,extended tickers,stable 14 to 24
0,0,320193,Apple Inc.,operating,3571.0,Electronic Computers,06 Technology,0,1,AAPL,...,ONE APPLE PARK WAY,NaN,CUPERTINO,CA,95014,CA,334111,True,"AAPL*,AAPL",True
1,1,789019,MICROSOFT CORP,operating,7372.0,Services-Prepackaged Software,06 Technology,1,1,MSFT,...,ONE MICROSOFT WAY,NaN,REDMOND,WA,98052-6399,WA,"511210,334614",True,MSFT,True
2,2,1045810,NVIDIA CORP,operating,3674.0,Semiconductors & Related Devices,04 Manufacturing,1,1,NVDA,...,2788 SAN TOMAS EXPRESSWAY,NaN,SANTA CLARA,CA,95051,CA,334413,True,NVDA,True
3,3,1652044,Alphabet Inc.,operating,7370.0,"Services-Computer Programming, Data Processing...",06 Technology,1,1,"GOOGL,GOOG",...,1600 AMPHITHEATRE PARKWAY,NaN,MOUNTAIN VIEW,CA,94043,CA,"518210,541511",True,"GOOG,GOOGL,GOOG*",True
4,4,1326801,"Meta Platforms, Inc.",operating,7370.0,"Services-Computer Programming, Data Processing...",06 Technology,0,1,"META,FB",...,1 META WAY,NaN,MENLO PARK,CA,94025,CA,"518210,541511",False,"FB*,FB,META",True
5,5,1730168,Broadcom Inc.,operating,3674.0,Semiconductors & Related Devices,04 Manufacturing,0,1,"AVGO,BRCM",...,3421 HILLVIEW AVENUE,NaN,PALO ALTO,CA,94304,CA,334413,True,"BRCM,AVGO",True
6,6,1341439,ORACLE CORP,operating,7372.0,Services-Prepackaged Software,06 Technology,1,1,ORCL,...,2300 ORACLE WAY,NaN,AUSTIN,TX,78741,TX,"511210,334614",True,ORCL,True
7,7,1108524,"Salesforce, Inc.",operating,7372.0,Services-Prepackaged Software,06 Technology,1,1,CRM,...,SALESFORCE TOWER,415 MISSION STREET 3RD FL,SAN FRANCISCO,CA,94105,CA,"511210,334614",True,CRM,True
8,8,796343,ADOBE INC.,operating,7372.0,Services-Prepackaged Software,06 Technology,1,1,ADBE,...,345 PARK AVE,NaN,SAN JOSE,CA,95110-2704,CA,"511210,334614",True,ADBE,True
10,10,97745,THERMO FISHER SCIENTIFIC INC.,operating,3829.0,"Measuring & Controlling Devices, NEC",08 Industrial Applications and Services,1,1,TMO,...,168 THIRD AVENUE,NaN,WALTHAM,MA,02451,MA,"339112,334514,334519",True,TMO,True
12,12,858877,"CISCO SYSTEMS, INC.",operating,3576.0,Computer Communications Equipment,06 Technology,1,1,CSCO,...,170 WEST TASMAN DR,NaN,SAN JOSE,CA,95134-1706,CA,"334112,333316,334118,333318,334111",True,CSCO,True
13,13,313616,DANAHER CORP /DE/,operating,3823.0,"Industrial Instruments For Measurement, Displa...",08 Industrial Applications and Services,1,1,DHR,...,2200 PENNSYLVANIA AVE. N.W.,SUITE 800W,WASHINGTON,DC,20037-1701,DC,334513,True,DHR,True
14,14,896878,INTUIT INC.,operating,7372.0,Services-Prepackaged Software,06 Technology,0,1,INTU,...,2700 COAST AVENUE,NaN,MOUNTAIN VIEW,CA,94043,CA,"511210,334614",True,INTU,True
15,15,97476,TEXAS INSTRUMENTS INC,operating,3674.0,Semiconductors & Related Devices,04 Manufacturing,0,1,TXN,...,P.O. BOX 660199,NaN,DALLAS,TX,75266,TX,334413,True,TXN,True
16,16,51143,INTERNATIONAL BUSINESS MACHINES CORP,operating,3570.0,Computer & office Equipment,06 Technology,1,1,IBM,...,1 NEW ORCHARD ROAD,NaN,ARMONK,NY,10504,NY,"334112,334111",True,IBM,True
17,17,6951,APPLIED MATERIALS INC /DE,operating,3674.0,Semiconductors & Related Devices,04 Manufacturing,1,1,AMAT,...,3050 BOWERS AVE,NaN,SANTA CLARA,CA,95054-3299,CA,334413,True,AMAT,True
19,19,732712,VERIZON COMMUNICATIONS INC,operating,4813.0,Telephone Communications (No Radiotelephone),06 Technology,1,1,VZ,...,1095 AVENUE OF THE AMERICAS,NaN,NEW YORK,NY,10036,NY,"517911,517311",True,VZ,True
20,20,18230,CATERPILLAR INC,operating,3531.0,Construction Machinery & Equip,06 Technology,1,1,CAT,...,5205 N. O'CONNOR BOULEVARD,SUITE 100,IRVING,TX,75039,TX,"333120,333923,336510",True,CAT,True
21,21,1166691,COMCAST CORP,operating,4841.0,Cable & Other Pay Television Services,06 Technology,1,1,"CMCSA,CCZ",...,ONE COMCAST CENTER,NaN,PHILADELPHIA,PA,19103-2838,PA,"515210,517311",True,"CMCSA,CCZ",True
22,22,732717,AT&T INC.,operating,4813.0,Telephone Communications (No Radiotelephone),06 Technology,1,1,"T,TBB,TBC,T-PA,T-PC",...,208 S. AKARD ST,NaN,DALLAS,TX,75202,TX,"517911,517311",True,"T-PA,TBB,T,TBC,T-PC",True
23,23,723125,MICRON TECHNOLOGY INC,operating,3674.0,Semiconductors & Related Devices,04 Manufacturing,0,1,MU,...,8000 S FEDERAL WAY,PO BOX 6,BOISE,ID,83716-9632,ID,334413,True,MU,True
24,24,1551182,Eaton Corp plc,operating,3590.0,Misc Industrial & Commercial Machinery & Equip...,06 Technology,0,1,ETN,...,30 PEMBROKE ROAD,EATON HOUSE,DUBLIN,L2,DUBLIN 4,Ireland,"332710,336390,333318,332999,332813,333999",False,ETN,True
25,25,707549,LAM RESEARCH CORP,operating,3559.0,"Special Industry Machinery, NEC",06 Technology,0,1,LRCX,...,4650 CUSHING BLVD,NaN,FREMONT,CA,94538,CA,"333249,333318,332410,333111,333242",False,LRCX,True
27,27,6281,ANALOG DEVICES INC,operating,3674.0,Semiconductors & Related Devices,04 Manufacturing,0,1,ADI,...,ONE ANALOG WAY,NaN,WILMINGTON,MA,01887,MA,334413,True,ADI,True
29,29,1613103,Medtronic plc,operating,3845.0,Electromedical & Electrotherapeutic Apparatus,08 Industrial Applications and Services,1,1,MDT,...,BUILDING TWO PARKMORE BUSINESS PARK WEST,NaN,GALWAY,L2,1,Ireland,"334517,334510",True,MDT,True
30,30,8670,AUTOMATIC DATA PROCESSING INC,operating,7374.0,Services-Computer Processing & Data Preparation,06 Technology,1,1,ADP,...,ONE ADP BOULVARD,NaN,ROSELAND,NJ,07068,NJ,518210,True,ADP,True
31,31,315189,DEERE & CO,operating,3523.0,Farm Machinery & Equipment,06 Technology,1,1,DE,...,ONE JOHN DEERE PLACE,NaN,MOLINE,IL,61265-8098,IL,"332216,333922,332323,333111",True,DE,True
34,34,820313,AMPHENOL CORP /DE/,operating,3678.0,Electronic Connectors,04 Manufacturing,0,1,APH,...,358 HALL AVE,NaN,WALLINGFORD,CT,06492,CT,"334418,334419,334515,334310,334220",True,APH,True
39,39,49826,ILLINOIS TOOL WORKS INC,operating,3560.0,General Industrial Machinery & Equipment,06 Technology,0,1,ITW,...,155 HARLEM AVENUE,NaN,GLENVIEW,IL,60025,IL,"314999,333414,333999",True,ITW,True
43,43,882835,ROPER TECHNOLOGIES INC,operating,3823.0,"Industrial Instruments For Measurement, Displa...",08 Industrial Applications and Services,0,1,ROP,...,6496 UNIVERSITY PARKWAY,NaN,SARASOTA,FL,34240,FL,334513,True,ROP,True
45,45,769397,"Autodesk, Inc.",operating,7372.0,Services-Prepackaged Software,06 Technology,1,1,ADSK,...,"ONE MARKET, STE. 400.",NaN,SAN FRANCISCO,CA,94105,CA,"511210,334614",True,ADSK,True
47,47,833444,Johnson Controls International plc,operating,3585.0,Air-Cond & Warm Air Heatg Equip & Comm & Indl ...,06 Technology,1,1,JCI,...,ONE ALBERT QUAY,ALBERT QUAY,CORK,L2,00000,Ireland,333415,True,JCI,True
49,49,827054,MICROCHIP TECHNOLOGY INC,operating,3674.0,Semiconductors & Related Devices,04 Manufacturing,1,1,MCHP,...,2355 W CHANDLER BLVD,NaN,CHANDLER,AZ,85224-6199,AZ,334413,True,MCHP,True
50,50,26172,CUMMINS INC,operating,3510.0,Engines & Turbines,06 Technology,1,1,CMI,...,500 JACKSON ST,BOX 3005 MAIL CODE 93050,COLUMBUS,IN,47202-3005,IN,"333618,333611,336390",True,CMI,True
51,51,712515,ELECTRONIC ARTS INC.,operating,7372.0,Services-Prepackaged Software,06 Technology,0,1,EA,...,209 REDWOOD SHORES PARKWAY,NaN,REDWOOD CITY,CA,94065,CA,"511210,334614",True,EA,True
53,53,1037868,AMETEK INC/,operating,3823.0,"Industrial Instruments For Measurement, Displa...",08 Industrial Applications and Services,0,1,AME,...,1100 CASSATT ROAD,NaN,BERWYN,PA,19312,PA,334513,False,AME,True
54,54,1058290,COGNIZANT TECHNOLOGY SOLUTIONS CORP,operating,7371.0,Services-Computer Programming Services,06 Technology,1,1,CTSH,...,"300 FRANK W. BURR BLVD., STE. 36, 6 FL.",NaN,TEANECK,NJ,07666,NJ,541511,True,CTSH,True
57,57,47217,HP INC,operating,3570.0,Computer & office Equipment,06 Technology,1,1,HPQ,...,1501 PAGE MILL ROAD,NaN,PALO ALTO,CA,94304,CA,"334112,334111",True,HPQ,True
60,60,1524472,Xylem Inc.,operating,3561.0,Pumps & Pumping Equipment,06 Technology,0,1,XYL,...,301 WATER STREET SE,NaN,WASHINGTON,DC,20003,DC,333914,True,XYL,True
61,61,1024478,"ROCKWELL AUTOMATION, INC",operating,3829.0,"Measuring & Controlling Devices, NEC",08 Industrial Applications and Services,0,1,ROK,...,1201 SOUTH 2ND STREET,NaN,MILWAUKEE,WI,53204,WI,"339112,334514,334519",True,ROK,True
63,63,1002047,"NetApp, Inc.",operating,3572.0,Computer Storage Devices,06 Technology,0,1,NTAP,...,3060 OLSEN DRIVE,NaN,SAN JOSE,CA,95128,CA,334112,True,NTAP,True
67,67,29905,DOVER Corp,operating,3530.0,"Construction, Mining & Materials Handling Mach...",06 Technology,1,1,DOV,...,3005 HIGHLAND PARKWAY,SUITE 200,DOWNERS GROVE,IL,60515,IL,333131,True,DOV,True
74,74,1137789,Seagate Technology Holdings plc,operating,3572.0,Computer Storage Devices,06 Technology,1,1,STX,...,121 WOODLANDS AVENUE 5,NaN,SINGAPORE,U0,739009,Singapore,334112,False,STX,True
75,75,106040,WESTERN DIGITAL CORP,operating,3572.0,Computer Storage Devices,06 Technology,0,1,WDC,...,5601 GREAT OAKS PARKWAY,NaN,SAN JOSE,CA,95119,CA,334112,True,WDC,True
81,81,1754301,Fox Corp,operating,4833.0,Television Broadcasting Stations,06 Technology,0,1,"FOXA,FOX",...,1211 AVENUE OF THE AMERICAS,NaN,NEW YORK,NY,10036,NY,515120,True,"FOX,FOXA",True
82,82,1014473,VERISIGN INC/CA,operating,7371.0,Services-Computer Programming Services,06 Technology,0,1,VRSN,...,12061 BLUEMONT WAY,ATTN: GENERAL COUNSEL,RESTON,VA,20190,VA,541511,True,VRSN,True
88,88,77360,PENTAIR plc,operating,3550.0,Special Industry Machinery (No Metalworking Ma...,06 Technology,0,1,PNR,...,"REGAL HOUSE, 70 LONDON ROAD",TWICKENHAM,LONDON,X0,TW13QS,United Kingdom,"333242,333249,333318,333111,332410",False,PNR,True
91,91,1043604,JUNIPER NETWORKS INC,operating,3576.0,Computer Communications Equipment,06 Technology,1,1,JNPR,...,1133 INNOVATION WAY,NaN,SUNNYVALE,CA,94089,CA,"334112,333316,334118,333318,334111",True,JNPR,True
95,95,1048695,"F5, INC.",operating,3576.0,Computer Communications Equipment,06 Technology,0,1,FFIV,...,801 5TH AVENUE,NaN,SEATTLE,WA,98104,WA,"334112,333316,334118,333318,334111",True,FFIV,True
98,98,46080,"HASBRO, INC.",operating,3944.0,"Games, Toys & Children's Vehicles (No Dolls & ...",04 Manufacturing,0,1,HAS,...,1027 NEWPORT AVE,P O BOX 1059,PAWTUCKET,RI,02861,RI,"339930,336991",True,HAS,True

In [12]:
lst_naics_str=list(df_tech_500.naics)

In [13]:
lst_naics_set=[set(ele_str.split(",")) for ele_str in lst_naics_str]

below is a function that union a list of sets.

In [15]:
def lst_set_union(lst_set): 
    union_set=set()
    for ele_set in lst_set: 
        union_set=union_set.union(ele_set)
    return union_set

In [16]:
set_naics=lst_set_union(lst_naics_set)

Below is the naics we care about, it seems a bit too long, and I only have a normal machine, so lets shorten it by industry.

In [17]:
set_naics

{'314999',
 '332216',
 '332323',
 '332410',
 '332710',
 '332813',
 '332999',
 '333111',
 '333120',
 '333131',
 '333132',
 '333242',
 '333249',
 '333316',
 '333318',
 '333414',
 '333415',
 '333611',
 '333618',
 '333914',
 '333922',
 '333923',
 '333992',
 '333999',
 '334111',
 '334112',
 '334118',
 '334210',
 '334220',
 '334310',
 '334413',
 '334418',
 '334419',
 '334510',
 '334512',
 '334513',
 '334514',
 '334515',
 '334517',
 '334519',
 '334613',
 '334614',
 '335121',
 '335122',
 '335129',
 '335999',
 '336390',
 '336510',
 '336991',
 '339112',
 '339930',
 '339940',
 '511210',
 '515120',
 '515210',
 '517311',
 '517312',
 '517911',
 '518210',
 '541511',
 '541512'}

In [21]:
set_naics_short=set()

for ele_str in set_naics: 
    set_naics_short.add(ele_str[:3]+"---")

In [22]:
set_naics_short

{'314---',
 '332---',
 '333---',
 '334---',
 '335---',
 '336---',
 '339---',
 '511---',
 '515---',
 '517---',
 '518---',
 '541---'}

Above is a list of shorten naics we care about, it might not be as detailed, but at least reasonable amount

In [19]:
df_naics_ppi=pd.read_table("../raw/ppi_and_cpi/ppi_ind_series.txt")

In [20]:
df_naics_ppi

,series_id,industry_code,product_code,seasonal,base_date,series_title,footnote_codes,begin_year,begin_period,end_year,end_period
0,PCU1133--1133--,1133--,1133--,U,198112,"PPI industry group data for Logging, not seaso...",NaN,1981,M12,2025,M01
1,PCU11331-11331-,11331-,11331-,U,198112,"PPI industry data for Logging, not seasonally ...",NaN,1981,M12,2025,M01
2,PCU113310113310,113310,113310,U,198112,"PPI industry data for Logging, not seasonally ...",NaN,1981,M12,2025,M01
3,PCU113310113310M,113310,113310M,U,198606,PPI industry data for Logging-Miscellaneous re...,NaN,1986,M06,2022,M07
4,PCU113310113310MM,113310,113310MM,U,198606,PPI industry data for Logging-Miscellaneous re...,NaN,1986,M06,1998,M08
...,...,...,...,...,...,...,...,...,...,...,...
4733,PCUATRNWRATRNWR,ATRNWR,ATRNWR,U,200612,PPI industry data for Transportation and wareh...,NaN,2006,M12,2025,M01
4734,PCUATTDSVATTDSV,ATTDSV,ATTDSV,U,200612,"PPI industry data for Services less trade, tra...",NaN,2006,M12,2025,M01
4735,PCUAWHLTRAWHLTR,AWHLTR,AWHLTR,U,200612,PPI industry data for Total wholesale trade in...,NaN,2006,M12,2025,M01
4736,PCUOMFG--OMFG--,OMFG--,OMFG--,U,198412,PPI industry group data for Total manufacturin...,NaN,1984,M12,2025,M01
4737,PCUOMIN--OMIN--,OMIN--,OMIN--,U,198412,PPI industry group data for Total mining indus...,NaN,1984,M12,2025,M01

In [26]:
df_naics_ppi[df_naics_ppi["industry_code"].isin(set_naics_short)]

,series_id,industry_code,product_code,seasonal,base_date,series_title,footnote_codes,begin_year,begin_period,end_year,end_period
819,PCU314---314---,314---,314---,U,200312,PPI industry sub-sector data for Textile produ...,NaN,2003,M12,2025,M01
2071,PCU332---332---,332---,332---,U,198412,PPI industry sub-sector data for Fabricated me...,NaN,1984,M12,2025,M01
2382,PCU333---333---,333---,333---,U,200312,PPI industry sub-sector data for Machinery man...,NaN,2003,M12,2025,M01
2753,PCU334---334---,334---,334---,U,200312,PPI industry sub-sector data for Computer & el...,NaN,2003,M12,2025,M01
2912,PCU335---335---,335---,335---,U,200312,PPI industry sub-sector data for Electrical eq...,NaN,2003,M12,2025,M01
3054,PCU336---336---,336---,336---,U,200312,PPI industry sub-sector data for Transportatio...,NaN,2003,M12,2025,M01
3375,PCU339---339---,339---,339---,U,200312,PPI industry sub-sector data for Miscellaneous...,NaN,2003,M12,2025,M01
4183,PCU517---517---,517---,517---,U,200312,PPI industry sub-sector data for Telecommunica...,NaN,2003,M12,2025,M01

There are some missing ones: 541---, 518---, 515---, 511---, we need to include one more digit in those naics to try again.

In [29]:
set_naics_short=set_naics_short.union({"5415--","5182--","5151--","5152--","5112--"})

In [30]:
df_naics_ppi[df_naics_ppi["industry_code"].isin(set_naics_short)]

,series_id,industry_code,product_code,seasonal,base_date,series_title,footnote_codes,begin_year,begin_period,end_year,end_period
819,PCU314---314---,314---,314---,U,200312,PPI industry sub-sector data for Textile produ...,NaN,2003,M12,2025,M01
2071,PCU332---332---,332---,332---,U,198412,PPI industry sub-sector data for Fabricated me...,NaN,1984,M12,2025,M01
2382,PCU333---333---,333---,333---,U,200312,PPI industry sub-sector data for Machinery man...,NaN,2003,M12,2025,M01
2753,PCU334---334---,334---,334---,U,200312,PPI industry sub-sector data for Computer & el...,NaN,2003,M12,2025,M01
2912,PCU335---335---,335---,335---,U,200312,PPI industry sub-sector data for Electrical eq...,NaN,2003,M12,2025,M01
3054,PCU336---336---,336---,336---,U,200312,PPI industry sub-sector data for Transportatio...,NaN,2003,M12,2025,M01
3375,PCU339---339---,339---,339---,U,200312,PPI industry sub-sector data for Miscellaneous...,NaN,2003,M12,2025,M01
4183,PCU517---517---,517---,517---,U,200312,PPI industry sub-sector data for Telecommunica...,NaN,2003,M12,2025,M01
4209,PCU5182--5182--,5182--,5182--,U,200312,PPI industry group data for Data processing an...,NaN,2003,M12,2025,M01

still missing: 5415--, 5151--, 5152--, 5112--.

5415--: Computer system design services (could not find similar, this is very annoying)

515---: broad casting (similar to 516---)

5112--: software publisher (similar to 5132--)

In [31]:
set_naics_short=set_naics_short.union({"516---","5132--"})

In [33]:
df_ppi_care=df_naics_ppi[df_naics_ppi["industry_code"].isin(set_naics_short)]

In [52]:
df_ppi_care

,series_id,industry_code,product_code,seasonal,base_date,series_title,footnote_codes,begin_year,begin_period,end_year,end_period
819,PCU314---314---,314---,314---,U,200312,PPI industry sub-sector data for Textile produ...,NaN,2003,M12,2025,M01
2071,PCU332---332---,332---,332---,U,198412,PPI industry sub-sector data for Fabricated me...,NaN,1984,M12,2025,M01
2382,PCU333---333---,333---,333---,U,200312,PPI industry sub-sector data for Machinery man...,NaN,2003,M12,2025,M01
2753,PCU334---334---,334---,334---,U,200312,PPI industry sub-sector data for Computer & el...,NaN,2003,M12,2025,M01
2912,PCU335---335---,335---,335---,U,200312,PPI industry sub-sector data for Electrical eq...,NaN,2003,M12,2025,M01
3054,PCU336---336---,336---,336---,U,200312,PPI industry sub-sector data for Transportatio...,NaN,2003,M12,2025,M01
3375,PCU339---339---,339---,339---,U,200312,PPI industry sub-sector data for Miscellaneous...,NaN,2003,M12,2025,M01
4145,PCU5132--5132--,5132--,5132--,U,200312,PPI industry group data for Software publisher...,NaN,2003,M12,2025,M01
4158,PCU516---516---,516---,516---,U,200312,"PPI industry sub-sector data for Broadcasting,...",NaN,2003,M12,2025,M01
4183,PCU517---517---,517---,517---,U,200312,PPI industry sub-sector data for Telecommunica...,NaN,2003,M12,2025,M01
4209,PCU5182--5182--,5182--,5182--,U,200312,PPI industry group data for Data processing an...,NaN,2003,M12,2025,M01

Now we try to download the data

In [53]:
df_ppi_care.columns

Index(['series_id                     ', 'industry_code', 'product_code',
       'seasonal', 'base_date', 'series_title', 'footnote_codes', 'begin_year',
       'begin_period', 'end_year', 'end_period'],
      dtype='object')

In [54]:
series_care=list(df_ppi_care["series_id                     "])

In [55]:
series_care=[ele_str[:15] for ele_str in series_care]

In [56]:
series_care

['PCU314---314---',
 'PCU332---332---',
 'PCU333---333---',
 'PCU334---334---',
 'PCU335---335---',
 'PCU336---336---',
 'PCU339---339---',
 'PCU5132--5132--',
 'PCU516---516---',
 'PCU517---517---',
 'PCU5182--5182--']

In [43]:
import requests
import json
import prettytable

In [62]:
headers = {'Content-type': 'application/json'}
data = json.dumps({"seriesid": series_care,"startyear":"2003", "endyear":"2012"})
p = requests.post('https://api.bls.gov/publicAPI/v2/timeseries/data/', data=data, headers=headers)
json_data = json.loads(p.text)
for series in json_data['Results']['series']:
    x=prettytable.PrettyTable(["series id","year","period","value","footnotes"])
    seriesId = series['seriesID']
    for item in series['data']:
        year = item['year']
        period = item['period']
        value = item['value']
        footnotes=""
        for footnote in item['footnotes']:
            if footnote:
                footnotes = footnotes + footnote['text'] + ','
        if 'M01' <= period <= 'M12':
            x.add_row([seriesId,year,period,value,footnotes[0:-1]])
    output = open("../raw/ppi_and_cpi/"+seriesId + '(03-12).txt','w')
    output.write (x.get_string())
    output.close()

In [63]:
headers = {'Content-type': 'application/json'}
data = json.dumps({"seriesid": series_care,"startyear":"2012", "endyear":"2020"})
p = requests.post('https://api.bls.gov/publicAPI/v2/timeseries/data/', data=data, headers=headers)
json_data = json.loads(p.text)
for series in json_data['Results']['series']:
    x=prettytable.PrettyTable(["series id","year","period","value","footnotes"])
    seriesId = series['seriesID']
    for item in series['data']:
        year = item['year']
        period = item['period']
        value = item['value']
        footnotes=""
        for footnote in item['footnotes']:
            if footnote:
                footnotes = footnotes + footnote['text'] + ','
        if 'M01' <= period <= 'M12':
            x.add_row([seriesId,year,period,value,footnotes[0:-1]])
    output = open("../raw/ppi_and_cpi/"+seriesId + '(12-20).txt','w')
    output.write (x.get_string())
    output.close()

In [64]:
headers = {'Content-type': 'application/json'}
data = json.dumps({"seriesid": series_care,"startyear":"2020", "endyear":"2025"})
p = requests.post('https://api.bls.gov/publicAPI/v2/timeseries/data/', data=data, headers=headers)
json_data = json.loads(p.text)
for series in json_data['Results']['series']:
    x=prettytable.PrettyTable(["series id","year","period","value","footnotes"])
    seriesId = series['seriesID']
    for item in series['data']:
        year = item['year']
        period = item['period']
        value = item['value']
        footnotes=""
        for footnote in item['footnotes']:
            if footnote:
                footnotes = footnotes + footnote['text'] + ','
        if 'M01' <= period <= 'M12':
            x.add_row([seriesId,year,period,value,footnotes[0:-1]])
    output = open("../raw/ppi_and_cpi/"+seriesId + '(20-25).txt','w')
    output.write (x.get_string())
    output.close()